version: '3.8'

services:
  # Production Django Backend
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - static_volume:/app/backend/staticfiles
    environment:
      - DEBUG=False
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_STORAGE_BUCKET=${GCP_STORAGE_BUCKET}
      - PUBMED_EMAIL=${PUBMED_EMAIL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/stats/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.prod.conf:/etc/nginx/nginx.conf
      - static_volume:/static:ro
      - ssl_certs:/etc/ssl/certs
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
  ssl_certs: 